### ISSUE TITLE
Missing css classes

### ISSUE THREAD

**Issue by inventionate** [theimerj/nova-medialibrary-field#2]
First, thank you very much for the wonderful work! I hope this is the right place to point out problems. While testing, I noticed that the layout of the upload buttons and the individual files is unfortunately a bit awkward. Aligning them with the previous design (for Nova 3) by adding appropriate CSS classes would be super. Here is a picture of how it currently looks (unfortunately in German):

<img width="270" alt="Bildschirmfoto 2022-05-14 um 07 44 21" src="https://user-images.githubusercontent.com/872787/168412655-25c82731-8f1a-44d3-8f2d-ca4196b747cf.png">

**Comment by repl6669** [comment]
@inventionate thank you for reporting. @kreejzak could you please have a look? Thank you.

**Comment by repl6669** [comment]
Fixed with #3 thank you @inventionate.
